# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.7'

# Define services
services:
  # App backend service
  app-server:
    # Configuration for building the docker image for the backend service
    build:
      context: anthill-app/Anthill-Server # Use an image built from the specified dockerfile in the `polling-app-server` directory.
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    depends_on: 
      - db # This service depends on mariadb. Start that first.
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

  # Frontend Service 
  app-client:
    build:
      context: anthill-client # Use an image built from the specified dockerfile in the `polling-app-client` directory.
      dockerfile: Dockerfile
      args:
        - API_BASE_URL=http://localhost:8080
        - API_DOMAIN=localhost:8080
    ports:
      - "9090:80" # Forward the exposed port 80 on the container to port 80 on the host machine
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend

  # Database Service (Mariadb)
  db:
    image: mariadb
    ports:
      - "33061:3306"
    restart: always
    environment:
      MYSQL_DATABASE: anthill
      MYSQL_USER: developer
      MYSQL_PASSWORD: pietracho12
      MYSQL_ROOT_PASSWORD: pietracho12!
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
  
# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend: